### ISSUE TITLE
INCLUDE directive corrupts equip_flags with few values

### ISSUE THREAD

**Issue by igorko** [igorko/FlareFramework#2]
When your items file includes another file which contains equip_flags with few values

**Comment by igorko** [comment]
@dorkster, can you look into it? You are more familiar with fileparser. I guess this issue is not present in engine...

**Comment by dorkster** [comment]
I'm not seeing any corruption:
![2015-05-25_175047](https://cloud.githubusercontent.com/assets/913982/7802580/a76f7c18-0306-11e5-9050-64f4cab83946.png)

However, I had to change all calls to `QString::toAscii()` and `QString::fromAscii()` to their Utf8 counterparts. The Ascii versions have been deprecated in the latest QT releases. Maybe that has something to do with this?

**Comment by dorkster** [comment]
Patch for my changes: https://gist.githubusercontent.com/dorkster/a1a954b686e78044c418/raw/cdb7e57c1081f8f15629c9498e4c3d0184c1b7f4/gistfile1.diff

**Comment by igorko** [comment]
I will check equip_flags once again. I was having recursive result when reading item properties, e.g. equip_flags=equip_flags=ranged... I will check again and provide testcase mod if needed.

**Comment by igorko** [comment]
Closing for now as I cannot reproduce this.
