### ISSUE TITLE
Main window size is too big for small screen resolutions

### ISSUE THREAD

**Issue by dorkster** [igorko/FlareFramework#7]
As someone cursed with a screen resolution of 1360x768, I'd like to see the ability to use a smaller main window. The contents of each tab could be placed in a "scrollbox" (not sure if this is what QT would call it).

**Comment by igorko** [comment]
Should make your pc happy https://github.com/igorko/FlareFramework/commit/24e1523e1940de0be4cd06a74502f639f87d608b Please test.

**Comment by dorkster** [comment]
That's perfect. Thanks.
